services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: database
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: ${SA_PASSWORD}
    ports:
      - "1433:1433"  
    volumes:
      - sql-data:/var/opt/mssql
    healthcheck:
      test: ["CMD", "timeout", "10s", "bash", "-c", "cat < /dev/null > /dev/tcp/localhost/1433"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
  api:
    depends_on:
      db:
        condition: service_healthy
    build:
      context: .               
      dockerfile: src/MoneyKeeper/Dockerfile
    container_name: api
    ports:
      - "3000:8080"            
      - "3001:8081"             
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - ConnectionStrings__DefaultConnection=Server=db;Database=MoneyManagement;User Id=sa;Password=${SA_PASSWORD};TrustServerCertificate=true
      - JwtOptions__SecretKey=${JwtOptions__SecretKey}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s

volumes:
  sql-data:

